// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pg_db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Destination struct {
	ID        int32           `json:"id"`
	City      string          `json:"city"`
	Country   string          `json:"country"`
	Clues     json.RawMessage `json:"clues"`
	FunFacts  json.RawMessage `json:"fun_facts"`
	Trivia    json.RawMessage `json:"trivia"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Friend struct {
	ID        int32     `json:"id"`
	Player1ID uuid.UUID `json:"player1_id"`
	Player2ID uuid.UUID `json:"player2_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Player struct {
	ID             uuid.UUID `json:"id"`
	Avatar         string    `json:"avatar"`
	Name           string    `json:"name"`
	CorrectAnswers int32     `json:"correct_answers"`
	TotalAttempts  int32     `json:"total_attempts"`
	Score          float64   `json:"score"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Session struct {
	ID             int32         `json:"id"`
	UserID         uuid.UUID     `json:"user_id"`
	Destinations   []int32       `json:"destinations"`
	Score          float64       `json:"score"`
	TotalAttempted sql.NullInt32 `json:"total_attempted"`
	Correct        sql.NullInt32 `json:"correct"`
}
