// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pg_db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFriend(ctx context.Context, arg *AddFriendParams) error
	CreateNewPlayer(ctx context.Context, arg *CreateNewPlayerParams) error
	GetDestinationByID(ctx context.Context, id int32) (*GetDestinationByIDRow, error)
	GetFriendsIdListOfPlayerByID(ctx context.Context, player1ID uuid.UUID) ([]uuid.UUID, error)
	GetLeaderboardDetails(ctx context.Context, dollar_1 []uuid.UUID) ([]*GetLeaderboardDetailsRow, error)
	GetLeaderboardForFriends(ctx context.Context, id uuid.UUID) ([]*GetLeaderboardForFriendsRow, error)
	GetPlayerById(ctx context.Context, id uuid.UUID) (*Player, error)
	GetRandomDestinations(ctx context.Context, dollar_1 []int32) ([]*GetRandomDestinationsRow, error)
	GetRandomDestinationsForQuestions(ctx context.Context) ([]*GetRandomDestinationsForQuestionsRow, error)
	UpdatePlayerScore(ctx context.Context, arg *UpdatePlayerScoreParams) error
}

var _ Querier = (*Queries)(nil)
