// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pg_db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFriend(ctx context.Context, arg *AddFriendParams) error
	CreateNewPlayer(ctx context.Context, arg *CreateNewPlayerParams) error
	CreateUserSession(ctx context.Context, arg *CreateUserSessionParams) error
	GetAllUserSessionByID(ctx context.Context, userID uuid.UUID) (int32, error)
	GetDestinationByID(ctx context.Context, id int32) (*GetDestinationByIDRow, error)
	GetFriendsIdListOfPlayerByID(ctx context.Context, player1ID uuid.UUID) ([]uuid.UUID, error)
	GetLeaderboardDetails(ctx context.Context, dollar_1 []uuid.UUID) ([]*GetLeaderboardDetailsRow, error)
	GetLeaderboardForFriends(ctx context.Context, id uuid.UUID) ([]*GetLeaderboardForFriendsRow, error)
	GetPlayerById(ctx context.Context, id uuid.UUID) (*Player, error)
	// -- name: GetRandomDestinationsForSessionQuestions :many
	// SELECT id, city, country, clues
	// FROM destinations
	// ORDER BY RANDOM()
	// LIMIT $1;
	GetRandomDestinationForSessions(ctx context.Context, arg *GetRandomDestinationForSessionsParams) ([]*GetRandomDestinationForSessionsRow, error)
	GetRandomDestinations(ctx context.Context, dollar_1 []int32) ([]*GetRandomDestinationsRow, error)
	GetRandomDestinationsForQuestions(ctx context.Context) ([]*GetRandomDestinationsForQuestionsRow, error)
	GetRandomDestinationsForSessionQuestions(ctx context.Context) ([]int32, error)
	GetUserSessionByID(ctx context.Context, arg *GetUserSessionByIDParams) (*Session, error)
	UpdatePlayerScore(ctx context.Context, arg *UpdatePlayerScoreParams) error
	UpdateUserSession(ctx context.Context, arg *UpdateUserSessionParams) error
}

var _ Querier = (*Queries)(nil)
